name: IMS Labs CI Pipeline

on:
  push:
    paths:
      - "Infrastructure Management Solutions/Lab1"

jobs:
  create-docker-image:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./Infrastructure Management Solutions/Lab1
          file: Dockerfile
          push: true
          tags: ims-lab1:latest